/**
  ******************************************************************************
  * @file    system_stm32l1xx.c
  * @author  MCD Application Team
  * @version V4.0.0
  * @date    21-January-2013
  * @brief   CMSIS Cortex-M3 Device Peripheral Access Layer System Source File.
  *          This file contains the system clock configuration for STM32L1xx Ultra
  *          Low Power devices, and is generated by the clock configuration
  *          tool "STM32L1xx_Clock_Configuration_V1.1.0.xls".
  *             
  * 1.  This file provides two functions and one global variable to be called from 
  *     user application:
  *      - SystemInit(): Setups the system clock (System clock source, PLL Multiplier
  *                      and Divider factors, AHB/APBx prescalers and Flash settings),
  *                      depending on the configuration made in the clock xls tool. 
  *                      This function is called at startup just after reset and 
  *                      before branch to main program. This call is made inside
  *                      the "startup_stm32l1xx_xx.s" file.
  *                        
  *      - SystemCoreClock variable: Contains the core clock (HCLK), it can be used
  *                                  by the user application to setup the SysTick 
  *                                  timer or configure other parameters.
  *                                     
  *      - SystemCoreClockUpdate(): Updates the variable SystemCoreClock and must
  *                                 be called whenever the core clock is changed
  *                                 during program execution.   
  *      
  * 2. After each device reset the MSI (2.1 MHz Range) is used as system clock source.
  *    Then SystemInit() function is called, in "startup_stm32l1xx_xx.s" file, to
  *    configure the system clock before to branch to main program.    
  *    
  * 3. If the system clock source selected by user fails to startup, the SystemInit()
  *    function will do nothing and MSI still used as system clock source. User can 
  *    add some code to deal with this issue inside the SetSysClock() function.
  * 
  * 4. The default value of HSE crystal is set to 8MHz, refer to "HSE_VALUE" define
  *    in "stm32l1xx.h" file. When HSE is used as system clock source, directly or
  *    through PLL, and you are using different crystal you have to adapt the HSE
  *    value to your own configuration.
  * 
  * 5. This file configures the system clock as follows:  
  *=============================================================================
  *                         System Clock Configuration
  *=============================================================================
  *        System Clock source          | PLL(HSE)
  *-----------------------------------------------------------------------------
  *        SYSCLK                       | 32000000 Hz
  *-----------------------------------------------------------------------------
  *        HCLK                         | 32000000 Hz
  *-----------------------------------------------------------------------------
  *        AHB Prescaler                | 1
  *-----------------------------------------------------------------------------
  *        APB1 Prescaler               | 1
  *-----------------------------------------------------------------------------
  *        APB2 Prescaler               | 1
  *-----------------------------------------------------------------------------
  *        HSE Frequency                | 8000000 Hz
  *-----------------------------------------------------------------------------
  *        PLL DIV                      | 3
  *-----------------------------------------------------------------------------
  *        PLL MUL                      | 12
  *-----------------------------------------------------------------------------
  *        VDD                          | 3.3 V
  *-----------------------------------------------------------------------------
  *        Vcore                        | 1.8 V (Range 1)
  *-----------------------------------------------------------------------------
  *        Flash Latency                | 1 WS
  *-----------------------------------------------------------------------------
  *        SDIO clock (SDIOCLK)         | 48000000 Hz
  *-----------------------------------------------------------------------------
  *        Require 48MHz for USB clock  | Disabled
  *-----------------------------------------------------------------------------
  *=============================================================================
  */

#include "stm32l1xx.h"
/*!< Uncomment the following line if you need to relocate your vector Table in Internal SRAM. */ 
/* #define VECT_TAB_SRAM */
#define VECT_TAB_OFFSET  0x0	/*!< Vector Table base offset field. 
									This value must be a multiple of 0x200. */
uint32_t SystemCoreClock    = 32000000;
const uint8_t PLLMulTable[9] = {3, 4, 6, 8, 12, 16, 24, 32, 48};
const uint8_t AHBPrescTable[16] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9};

static void SetSysClock(void);

/**
  * @brief  Setup the microcontroller system.
  *         Initialize the Embedded Flash Interface, the PLL and update the 
  *         SystemCoreClock variable.
  * @param  None
  * @retval None
  */
void SystemInit (void)
{
	RCC_TypeDef * rcc = RCC;

	rcc->CR |= RCC_CR_MSION;

	/*!< Reset SW[1:0], HPRE[3:0], PPRE1[2:0], PPRE2[2:0], MCOSEL[2:0] and MCOPRE[2:0] bits */
	rcc->CFGR &= (uint32_t)0x88FFC00C;

	rcc->CR &= ~(RCC_CR_CSSON | RCC_CR_PLLON | RCC_CR_HSEON | RCC_CR_HSION);
	rcc->CR &= !RCC_CR_HSEBYP;

	/*!< Reset PLLSRC, PLLMUL[3:0] and PLLDIV[1:0] bits */
	rcc->CFGR &= (uint32_t)0xFF02FFFF;

	rcc->CIR = 0;	/*!< Disable all interrupts */

#ifdef DATA_IN_ExtSRAM
	SystemInit_ExtMemCtl(); 
#endif /* DATA_IN_ExtSRAM */
    
	/* Configure the System clock frequency, AHB/APBx prescalers and Flash settings */
	SetSysClock();

#ifdef VECT_TAB_SRAM
	SCB->VTOR = SRAM_BASE | VECT_TAB_OFFSET; /* Vector Table Relocation in Internal SRAM. */
#else
	SCB->VTOR = FLASH_BASE | VECT_TAB_OFFSET; /* Vector Table Relocation in Internal FLASH. */
#endif
}

/**
  * @brief  Update SystemCoreClock according to Clock Register Values
  *         The SystemCoreClock variable contains the core clock (HCLK), it can
  *         be used by the user application to setup the SysTick timer or configure
  *         other parameters.
  *           
  * @note   Each time the core clock (HCLK) changes, this function must be called
  *         to update SystemCoreClock variable value. Otherwise, any configuration
  *         based on this variable will be incorrect.         
  *     
  * @note   - The system frequency computed by this function is not the real 
  *           frequency in the chip. It is calculated based on the predefined 
  *           constant and the selected clock source:
  *             
  *           - If SYSCLK source is MSI, SystemCoreClock will contain the MSI 
  *             value as defined by the MSI range.
  *                                   
  *           - If SYSCLK source is HSI, SystemCoreClock will contain the HSI_VALUE(*)
  *                                              
  *           - If SYSCLK source is HSE, SystemCoreClock will contain the HSE_VALUE(**)
  *                          
  *           - If SYSCLK source is PLL, SystemCoreClock will contain the HSE_VALUE(**)
  *             or HSI_VALUE(*) multiplied/divided by the PLL factors.
  *         
  *         (*) HSI_VALUE is a constant defined in stm32l1xx.h file (default value
  *             16 MHz) but the real value may vary depending on the variations
  *             in voltage and temperature.   
  *    
  *         (**) HSE_VALUE is a constant defined in stm32l1xx.h file (default value
  *              8 MHz), user has to ensure that HSE_VALUE is same as the real
  *              frequency of the crystal used. Otherwise, this function may
  *              have wrong result.
  *                
  *         - The result of this function could be not correct when using fractional
  *           value for HSE crystal.
  * @param  None
  * @retval None
  */
void SystemCoreClockUpdate (void)
{
	RCC_TypeDef * rcc = RCC;
	uint32_t pllmul, plldiv, msirange, clock;

	/* Get SYSCLK source -------------------------------------------------------*/
	switch (rcc->CFGR & RCC_CFGR_SWS)
	{
	case RCC_CFGR_SWS_MSI:	/* MSI used as system clock */
		msirange = (rcc->ICSCR & RCC_ICSCR_MSIRANGE) >> 13;
		clock = (32768ul * (1ul << (msirange + 1)));
		break;
	case RCC_CFGR_SWS_HSI:	/* HSI used as system clock */
		clock = HSI_VALUE;
		break;
	case RCC_CFGR_SWS_HSE:	/* HSE used as system clock */
		clock = HSE_VALUE;
		break;
	case RCC_CFGR_SWS_PLL:	/* PLL used as system clock */
		/* Get PLL clock source and multiplication factor ----------------------*/
		pllmul = PLLMulTable[((rcc->CFGR & RCC_CFGR_PLLMUL) >> 18)];
		plldiv = ((rcc->CFGR & RCC_CFGR_PLLDIV) >> 22) + 1;

		if ((rcc->CFGR & RCC_CFGR_PLLSRC) == RCC_CFGR_PLLSRC_HSI)
			/* HSI oscillator clock selected as PLL clock entry */
			clock = (((HSI_VALUE) * pllmul) / plldiv);
		else
			/* HSE selected as PLL clock entry */
			clock = (((HSE_VALUE) * pllmul) / plldiv);
		break;
	default:	/* MSI used as system clock */
		msirange = (rcc->ICSCR & RCC_ICSCR_MSIRANGE) >> 13;
		clock = (32768ul * (1ul << (msirange + 1)));
		break;
	}
	/* Compute HCLK clock frequency --------------------------------------------*/
	/* Get HCLK prescaler */
	/* HCLK clock frequency */
	SystemCoreClock = (clock >> AHBPrescTable[((rcc->CFGR & RCC_CFGR_HPRE) >> 4)]);
}

/**
  * @brief  Configures the System clock frequency, AHB/APBx prescalers and Flash 
  *         settings.
  * @note   This function should be called only once the RCC clock configuration  
  *         is reset to the default reset state (done in SystemInit() function).
  * @param  None
  * @retval None
  */
static void SetSysClock(void)
{
	RCC_TypeDef * rcc = RCC;
	uint32_t StartUpCounter = 0;

	/* SYSCLK, HCLK, PCLK2 and PCLK1 configuration ---------------------------*/
	/* Enable HSE */
	rcc->CR |= RCC_CR_HSEON;

	/* Wait till HSE is ready and if Time out is reached exit */
	
	for (StartUpCounter = 0;
		(rcc->CR & RCC_CR_HSERDY) == 0 && StartUpCounter != HSE_STARTUP_TIMEOUT;
		StartUpCounter++)
		__NOP();

	FLASH->ACR |= FLASH_ACR_ACC64;		/* Enable 64-bit access */
	FLASH->ACR |= FLASH_ACR_PRFTEN;		/* Enable Prefetch Buffer */
	FLASH->ACR |= FLASH_ACR_LATENCY;	/* Flash 1 wait state */
	rcc->APB1ENR |= RCC_APB1ENR_PWREN;	/* Power enable */
	PWR->CR = PWR_CR_VOS_0;				/* Select the Voltage Range 1 (1.8 V) */

	/* Wait Until the Voltage Regulator is ready */
	while ((PWR->CSR & PWR_CSR_VOSF) != RESET)
		;

	rcc->CFGR |= RCC_CFGR_HPRE_DIV1;	/* HCLK = SYSCLK /1*/
	rcc->CFGR |= RCC_CFGR_PPRE2_DIV1;	/* PCLK2 = HCLK /1*/
	rcc->CFGR |= RCC_CFGR_PPRE1_DIV1;	/* PCLK1 = HCLK /1*/

	rcc->CFGR &= ~(RCC_CFGR_PLLSRC | RCC_CFGR_PLLMUL | RCC_CFGR_PLLDIV);

	if ((rcc->CR & RCC_CR_HSERDY) != RESET)
	{	/*  PLL configuration from HSE */
		rcc->CFGR |= (RCC_CFGR_PLLSRC_HSE | RCC_CFGR_PLLMUL12 | RCC_CFGR_PLLDIV3);
		StartUpCounter = 1;
	}
	else
	{	/*  PLL configuration from HSI */
		rcc->CR &= ~RCC_CR_HSEON;
		rcc->CR |= RCC_CR_HSION;
		for(StartUpCounter = 0;
			(rcc->CR & RCC_CR_HSIRDY) == 0 && StartUpCounter != HSI_STARTUP_TIMEOUT;
			StartUpCounter++)
			__NOP();

		if ((rcc->CR & RCC_CR_HSIRDY) != RESET)
		{
			rcc->CFGR |= (RCC_CFGR_PLLSRC_HSI | RCC_CFGR_PLLMUL6 | RCC_CFGR_PLLDIV3);
			StartUpCounter = 1;
		}
		else
		{
			rcc->CR &= ~RCC_CR_HSION;
			StartUpCounter = 0;
		}
	}
	
	if (StartUpCounter == 1)
	{
		rcc->CR |= RCC_CR_PLLON;		/* Enable PLL */
		while ((rcc->CR & RCC_CR_PLLRDY) == 0)
			;							/* Wait till PLL is ready */

		rcc->CFGR &= ~RCC_CFGR_SW;		/* Select PLL as system clock source */
		rcc->CFGR |= RCC_CFGR_SW_PLL;

		/* Wait till PLL is used as system clock source */
		while ((rcc->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL)
			;
	}
}
