namespace SemtechLib.Devices.SX1276.Enumerations
{
	public enum OokPeakThreshDecEnum
	{
		EVERY_1_CHIPS_1_TIMES,
		EVERY_2_CHIPS_1_TIMES,
		EVERY_4_CHIPS_1_TIMES,
		EVERY_8_CHIPS_1_TIMES,
		EVERY_1_CHIPS_2_TIMES,
		EVERY_1_CHIPS_4_TIMES,
		EVERY_1_CHIPS_8_TIMES,
		EVERY_1_CHIPS_16_TIMES,
	}
}
